### ISSUE TITLE
Returns an error

### ISSUE THREAD

**Issue by utsavsinha** [sofiabravo103/builder#1]
How can I generate the data? I tried the following:

uutsav@ubuntu:~/builder-master$ python builder.py -o my_output_file --autotiny
Traceback (most recent call last):
  File "builder.py", line 1101, in <module>
    main(sys.argv[1:])
  File "builder.py", line 1095, in main
    generate_datasets(arrival_arr)
  File "builder.py", line 1052, in generate_datasets
    create_dataset(arrival_arr.pop(),splitter)
  File "builder.py", line 1035, in create_dataset
    prepare_outputfile(intermediate_file_name, testcase_num, act_count)
  File "builder.py", line 950, in prepare_outputfile
    join_tuple_events(sorted_intermediate_file_name,act_count)
NameError: global name 'join_tuple_events' is not defined

**Comment by sofiabravo103** [comment]
@utsavsinha Let me know if you need anything else, the bug should be fixed now.

**Comment by utsavsinha** [comment]
Thanks, it is working now.
